spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: redispass
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

jwt:
  secret: your-very-secure-secret-key
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    liquibase: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

server:
  port: 8080

grpc:
  server:
    port: 9090