version: '3.8'

services:

  eureka-server:
    build: ./eureka-service
    ports:
      - "8761:8761"
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7
    command: redis-server --requirepass redispass
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    ports:
      - "9000:9000"  # API порт
      - "9001:9001"  # Консоль порт
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  minio-data: