spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - name: TokenValidationFilter
              args:
                excludePaths: /auth/login, /auth/register
                roles: ADMIN
        - id: photos3-service
          uri: lb://photos3-service
          predicates:
            - Path=/api/photos/**
          filters:
            - StripPrefix=1
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/tickets/**
          filters:
            - StripPrefix=1
            - name: TokenValidationFilter
              args:
                roles: USER, ADMIN
        - id: openapi-auth
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth-service/**
          filters:
            - RewritePath=/v3/api-docs/auth-service(?<segment>.*), /v3/api-docs$\{segment}
        - id: openapi-photos3
          uri: lb://photos3-service
          predicates:
            - Path=/v3/api-docs/photos3-service/**
          filters:
            - RewritePath=/v3/api-docs/photos3-service(?<segment>.*), /v3/api-docs$\{segment}
        - id: openapi-ticket
          uri: lb://ticket-service
          predicates:
            - Path=/v3/api-docs/ticket-service/**
          filters:
            - RewritePath=/v3/api-docs/ticket-service(?<segment>.*), /v3/api-docs$\{segment}
      filter:
        json-to-grpc:
          enabled: false
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

server:
  port: 8081

grpc:
  client:
    auth-service:
      address: static://localhost:9090
      negotiation-type: plaintext

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs/photoS3-Service
        name: Photo S3 Service
      - url: /v3/api-docs/auth-service
        name: Auth Service
    operations-sorter: alpha
    config-url: /v3/api-docs/swagger-config
  try-it-out-enabled: true

logging:
  level:
    root: INFO
    by.baes.gatewayservice: DEBUG