spring:
  application:
    name: photoS3-service
  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
  springdoc:
    api-docs:
      path: /v3/api-docs

server:
  port: 8082

cloud:
  aws:
    credentials:
      access-key: minioadmin
      secret-key: minioadmin
    region:
      static: us-east-1
    s3:
      endpoint: http://localhost:9000  # Для Docker
      bucket: photos
    stack:
      auto: false  # Отключаем автообнаружение AWS CloudFormation (не нужно для MinIO)

logging:
  level:
    root: INFO
    by.baes.photos3service: DEBUG
    org.springframework.cloud.aws: DEBUG